# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nimGameLayout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import nimSupport

class NimUI(object):
    def setupUi(self, NimGUI):
        NimGUI.setObjectName("NimGUI")
        NimGUI.resize(500, 377)
        self.horizontalLayoutWidget = QtWidgets.QWidget(NimGUI)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 120, 301, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.stackDisplay = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.stackDisplay.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.stackDisplay.setContentsMargins(0, 0, 0, 0)
        self.stackDisplay.setSpacing(3)
        self.stackDisplay.setObjectName("stackDisplay")
        self.leftStack = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftStack.sizePolicy().hasHeightForWidth())
        self.leftStack.setSizePolicy(sizePolicy)
        self.leftStack.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.leftStack.setFont(font)
        self.leftStack.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.leftStack.setAlignment(QtCore.Qt.AlignCenter)
        self.leftStack.setObjectName("leftStack")
        self.stackDisplay.addWidget(self.leftStack)
        self.middleStack = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middleStack.sizePolicy().hasHeightForWidth())
        self.middleStack.setSizePolicy(sizePolicy)
        self.middleStack.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.middleStack.setFont(font)
        self.middleStack.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.middleStack.setAlignment(QtCore.Qt.AlignCenter)
        self.middleStack.setObjectName("middleStack")
        self.stackDisplay.addWidget(self.middleStack)
        self.rightStack = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightStack.sizePolicy().hasHeightForWidth())
        self.rightStack.setSizePolicy(sizePolicy)
        self.rightStack.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rightStack.setFont(font)
        self.rightStack.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.rightStack.setAlignment(QtCore.Qt.AlignCenter)
        self.rightStack.setObjectName("rightStack")
        self.stackDisplay.addWidget(self.rightStack)
        self.verticalLayoutWidget = QtWidgets.QWidget(NimGUI)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(180, 240, 114, 79))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.setButtons = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.setButtons.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.setButtons.setContentsMargins(0, 0, 0, 0)
        self.setButtons.setObjectName("setButtons")
        self.playButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.playButton.setObjectName("playButton")
        self.setButtons.addWidget(self.playButton)
        self.resetButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setMaximumSize(QtCore.QSize(250, 16777215))
        self.resetButton.setObjectName("resetButton")
        self.setButtons.addWidget(self.resetButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(NimGUI)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 170, 301, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.userInput = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_2)
        self.userInput.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.userInput.setContentsMargins(0, 0, 0, 0)
        self.userInput.setSpacing(3)
        self.userInput.setObjectName("userInput")
        self.leftStackInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftStackInput.sizePolicy().hasHeightForWidth())
        self.leftStackInput.setSizePolicy(sizePolicy)
        self.leftStackInput.setMaximumSize(QtCore.QSize(250, 16777215))
        self.leftStackInput.setObjectName("leftStackInput")
        self.userInput.addWidget(self.leftStackInput)
        self.middleStackInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.middleStackInput.sizePolicy().hasHeightForWidth())
        self.middleStackInput.setSizePolicy(sizePolicy)
        self.middleStackInput.setMaximumSize(QtCore.QSize(250, 16777215))
        self.middleStackInput.setObjectName("middleStackInput")
        self.userInput.addWidget(self.middleStackInput)
        self.rightStackInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightStackInput.sizePolicy().hasHeightForWidth())
        self.rightStackInput.setSizePolicy(sizePolicy)
        self.rightStackInput.setMaximumSize(QtCore.QSize(250, 16777215))
        self.rightStackInput.setObjectName("rightStackInput")
        self.userInput.addWidget(self.rightStackInput)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(NimGUI)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(160, 20, 160, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.nimTitle = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.nimTitle.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.nimTitle.setContentsMargins(0, 0, 0, 0)
        self.nimTitle.setSpacing(3)
        self.nimTitle.setObjectName("nimTitle")
        self.titleNIM = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleNIM.sizePolicy().hasHeightForWidth())
        self.titleNIM.setSizePolicy(sizePolicy)
        self.titleNIM.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.titleNIM.setFont(font)
        self.titleNIM.setAlignment(QtCore.Qt.AlignCenter)
        self.titleNIM.setObjectName("titleNIM")
        self.nimTitle.addWidget(self.titleNIM)

        self.retranslateUi(NimGUI)
        QtCore.QMetaObject.connectSlotsByName(NimGUI)

    def retranslateUi(self, NimGUI):
        _translate = QtCore.QCoreApplication.translate
        NimGUI.setWindowTitle(_translate("NimGUI", "NimGUI"))
        self.rightStack.setText(_translate("NimGUI", "0"))
        self.middleStack.setText(_translate("NimGUI", "0"))
        self.leftStack.setText(_translate("NimGUI", "0"))
        self.titleNIM.setText(_translate("NimGUI", "NIM"))
        self.playButton.setText(_translate("NimGUI", "PLAY"))
        self.resetButton.setText(_translate("NimGUI", "RESET"))


if __name__ == "__main__":
    import sys
    sys._excepthook = sys.excepthook
    def exception_hook(exctype, value, traceback):
        print(exctype, value, traceback)
        sys._excepthook(exctype, value, traceback)
        sys.exit(1)
    sys.excepthook = exception_hook
    
    app = QtWidgets.QApplication(sys.argv)
    #NimGUI = QtWidgets.QWidget()
    ui = NimUI()
    #ui.setupUi(NimGUI)
    NimGUI = nimSupport.GUIWindow(ui)
    NimGUI.show()
    sys.exit(app.exec_())

